// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHHcHAh9goyF0jWAA7Va8tXqdys0CG3NM',
    appId: '1:684786045615:web:aede488f170c59978cba5a',
    messagingSenderId: '684786045615',
    projectId: 'space-data-explorer',
    authDomain: 'space-data-explorer.firebaseapp.com',
    storageBucket: 'space-data-explorer.appspot.com',
    measurementId: 'G-28SMKJ4QYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8XQH3fdR0A7IPCspqQbvB3SoKf3Vq0c',
    appId: '1:684786045615:android:eb67f5103c2bdbdb8cba5a',
    messagingSenderId: '684786045615',
    projectId: 'space-data-explorer',
    storageBucket: 'space-data-explorer.appspot.com',
  );
}
