// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'stag.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN75Z01BKdTaEAhj5G9huzfvE2ppGGWBw',
    appId: '1:705512446254:web:72aad84a856b7beeb382bf',
    messagingSenderId: '705512446254',
    projectId: 'space-data-explorer-stag',
    authDomain: 'space-data-explorer-stag.firebaseapp.com',
    storageBucket: 'space-data-explorer-stag.appspot.com',
    measurementId: 'G-HT2B5P9QLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwKETC_GEWBDDbSnpUMxCUcegawO9hYM',
    appId: '1:705512446254:android:c81e2bc51ccc2010b382bf',
    messagingSenderId: '705512446254',
    projectId: 'space-data-explorer-stag',
    storageBucket: 'space-data-explorer-stag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQpxH6gmSb2c-Ap63lrtsEspHc_TVJ1Dk',
    appId: '1:705512446254:ios:dab87a53736e4ce7b382bf',
    messagingSenderId: '705512446254',
    projectId: 'space-data-explorer-stag',
    storageBucket: 'space-data-explorer-stag.appspot.com',
    iosBundleId: 'dev.hrishikesh-kadam.flutter.space-data-explorer.stag',
  );
}
