# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :get_play_version_code do |options|
    play_version_code = google_play_track_version_codes(
      package_name: options[:package_name],
      track: options[:track]
    )[0]
    puts "PLAY_VERSION_CODE=#{play_version_code}"
  end

end
