# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :get_play_version_code_max do |options|
    ENV["SUPPLY_PACKAGE_NAME"] = options[:package_name]
    productionVersionCodes = google_play_track_version_codes(
      track: 'production',
    ) rescue []
    betaVersionCodes = google_play_track_version_codes(
      track: 'beta',
    ) rescue []
    alphaVersionCodes = google_play_track_version_codes(
      track: 'alpha',
    ) rescue []
    internalVersionCodes = google_play_track_version_codes(
      track: 'internal',
    ) rescue []
    playVersionCodeMax = Set.new(
      productionVersionCodes +
      betaVersionCodes +
      alphaVersionCodes  +
      internalVersionCodes
    ).max
    playVersionCodeMax ||= 0
    UI.success "PLAY_VERSION_CODE_MAX=#{playVersionCodeMax}"
    playVersionCodeMax
  end
end
