# Note: jobs of ci-contributors.yml, ci-schedule.yml and ci-dispatch.yml should be in sync
name: ci-contributors

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci-contributors:
    name: CI for Contributors on ${{ matrix.runner }} using Flutter ${{ matrix.ref }}
    if: github.triggering_actor != 'dependabot[bot]'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest ]
        ref: [ stable, beta ]

    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'

      - run: echo '${{ toJSON(github) }}'

      - id: get-checkout-ref
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            CHECKOUT_REF="$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")"
          else
            CHECKOUT_REF="$GITHUB_REF_NAME"
          fi
          echo "CHECKOUT_REF=$CHECKOUT_REF" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-checkout-ref.outputs.CHECKOUT_REF }}

      - uses: hrishikesh-kadam/setup-flutter@v1
        with:
          ref: ${{ matrix.ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: ./tool/prerequisite.sh --contributor

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ matrix.runner }}-flutter-${{ matrix.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - run: ./tool/ci.sh

      - uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          name: ci-contributors-${{ matrix.runner }}-${{ matrix.ref }}

      - run: ./tool/web/deploy.sh
        if: matrix.ref == 'stable'
        env:
          FIREBASE_CONTRI_KEY: ${{ secrets.FIREBASE_CONTRI_KEY }}

      - run: ./tool/android/stop-gradle.sh
